id: ExtendedDAIC-16k-balanced
_target_: extended_daic_balanced.ExtendedDAIC_balanced

path: data/ExtendedDAIC-16k-balanced
features_subdir: log_mel_16k
index_column: filename
target_column: PHQ_Binary
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

# Balance training data by removing excess non-depressed patients
balance_seed: 42

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: grayscale
  base:
    - autrainer.transforms.Expand:
        size: 401
        axis: -2
    - autrainer.transforms.RandomCrop:
        size: 401
        axis: -2 