id: ExtendedDAIC-16k-fixed
_target_: extended_daic_fixed.ExtendedDAIC_fixed

path: data/ExtendedDAIC-16k-fixed
features_subdir: log_mel_16k
index_column: filename
target_column: PHQ_Binary
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR


transform:
  type: grayscale
  base:
    - autrainer.transforms.Expand:
        size: 501
        axis: -2
    - autrainer.transforms.RandomCrop:
        size: 501
        axis: -2