id: ExtendedDAIC-16k-augmented
_target_: extended_daic_augmented.ExtendedDAIC_augmented

path: data/ExtendedDAIC-16k-augmented
features_subdir: log_mel_16k
index_column: filename
target_column: PHQ_Binary
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

# Audio augmentation parameters for depressed samples
augmentation_factor: 2
pitch_shift_steps: [-2, -1, 1, 2]
time_stretch_rates: [0.9, 0.95, 1.05, 1.1]
augmentation_seed: 42

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: grayscale
  base:
    - autrainer.transforms.Expand:
        size: 401
        axis: -2
    - autrainer.transforms.RandomCrop:
        size: 401
        axis: -2 