defaults:
  - _self_
  - dataset: ExtendedDAIC
  - model: AlexNet-GRU
  - preprocessing: mel_spectrograms_avec2019
  - optimizer: Adam
  - scheduler: ReduceLROnPlateau
  - augmentation: None
  - plotting: Default

training_type: epoch
eval_frequency: 1
save_frequency: 5
batch_size: 4
inference_batch_size: 4
learning_rate: 0.0001
device: cpu
iterations: 50

progress_bar: true
continue_training: false
remove_continued_runs: true
save_train_outputs: false
save_dev_outputs: false
save_test_outputs: false

experiment_name: depression_detection_avec2019
experiment_id: depression_detection_avec2019
results_dir: results
seed: 42

checkpointing:
  save_top_k: 3
  monitor: val_accuracy
  mode: max 