defaults:
  - _autrainer_
  - _self_

results_dir: results
experiment_id: lstm
iterations: 50

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.0001
      dataset: ExtendedDAIC-lstm
      model: lstm
      optimizer: Adam 
      scheduler: StepLR
