defaults:
  - _autrainer_
  - _self_


results_dir: results
experiment_id: cnn10-binary-fixed-experiment
iterations: 50

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.0001
      dataset: ExtendedDAIC-16k-fixed
      model: CNN10-binary,CNN10-binary-frozen
      optimizer: Adam 
      scheduler: ReduceLROnPlateau
loggers:
  - wandb_logger.WandBLogger:
      output_dir: ${results_dir}/.wandb