defaults:
  - _autrainer_
  - _self_

results_dir: results
experiment_id: cnn10-binary-experiment
iterations: 50

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.001
      dataset: ExtendedDAIC-16k
      model: CNN10-binary,CNN10-binary-frozen
      optimizer: Adam