defaults:
  - _autrainer_
  - _self_

results_dir: results
experiment_id: default_2
iterations: 50

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.001
      dataset: ExtendedDAIC-16k
      model: EfficientNetB0-GRU, EfficientNetB2-GRU, VGG16-GRU
      optimizer: Adam