file_handler:
  autrainer.datasets.utils.AudioFileHandler:
    target_sample_rate: 16000
pipeline:
  - autrainer.transforms.StereoToMono
  - autrainer.transforms.PannMel:
      sample_rate: 16000
      window_size: 512  
      hop_size: 160
      mel_bins: 128
      fmin: 50
      fmax: 8000
      ref: 1.0
      amin: 1e-10
      top_db: null