id: AlexNet-GRU
_target_: depression_cnn_gru.AlexNetGRUModel
pretrained: true
gru_hidden_size: 64
gru_num_layers: 2
gru_dropout: 0.3
fc_hidden_size: 16
fc_dropout: 0.3
freeze_cnn: true

transform:
  type: grayscale 