id: EfficientNetB1-GRU
_target_: depression_cnn_gru.EfficientNetB1GRUModel
pretrained: true
gru_hidden_size: 64
gru_num_layers: 2
gru_dropout: 0.1
fc_hidden_size: 32
fc_dropout: 0.1
freeze_cnn: false

transform:
  type: image 